src/se/plushogskolan/web/domain/cars/Owner.java
package se.plushogskolan.web.domain.cars;

import java.util.HashSet;
import java.util.Set;

public class Owner {
	private String socialSecurityNo;
	private String firstName;
	private String lastName;
	private String address;
	private String zipCode;
	private String city;
	private Set<Car> cars = new HashSet<Car>();

	public Owner() {

	}

	public Owner(String socialSecurityNo, String firstName, String lastName, String address, String zipCode, String city) {
		setSocialSecurityNo(socialSecurityNo);
		setFirstName(firstName);
		setLastName(lastName);
		setAddress(address);
		setZipCode(zipCode);
		setCity(city);

	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public Set<Car> getCars() {
		return cars;
	}

	public void setCars(Set<Car> cars) {
		this.cars = cars;
	}

	public String getSocialSecurityNo() {
		return socialSecurityNo;
	}

	public void setSocialSecurityNo(String socialSecurityNo) {
		this.socialSecurityNo = socialSecurityNo;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getZipCode() {
		return zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getFullName() {

		return getFirstName() + " " + getLastName();
	}

	@Override
	public String toString() {
		return "Owner [socialSecurityNo=" + socialSecurityNo + ", firstName=" + firstName + ", lastName=" + lastName
				+ ", no of cars=" + cars.size() + "]";
	}

}

src/se/plushogskolan/web/servlets/sessions2/ShowCarServlet.java
package se.plushogskolan.web.servlets.sessions2;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.log4j.Logger;

public class ShowCarServlet extends AbstractSessionServlet {

	private static final long serialVersionUID = 1L;
	private Logger log = Logger.getLogger(ShowCarServlet.class);

	@Override
	protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {

		log.debug("ShowCarServlet.doGet()");
	}

	@Override
	protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {

		log.debug("ShowCarServlet.doPost()");

	}

}

WebContent/WEB-INF/jsp/plusverkstaden/EditCar.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>

<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="myDate" uri="myFunctions"%>
<%@ page import="java.util.*"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Edit Cars</title>
<link rel="stylesheet"
	href="<%=request.getContextPath()%>/styles/Cars.css">
</head>
<body>

	<c:set var="title" value="Edit car" />
	<c:set var="submit" value="Update car" />

	<c:if test="${newCar}">
		<c:set var="title" value="Create new car" />
		<c:set var="submit" value="Create car" />
	</c:if>

	<jsp:include page="header.jsp">

		<jsp:param value="${title}" name="title" />
		<jsp:param value="${myDate:today()}" name="date" />

	</jsp:include>

	<c:if test="${invalidReg}">
		<p class="warning">Missing reg number</p>
	</c:if>
	<c:if test="${invalidYear}">
		<p class="warning">Invalid year, must be between 1970 and 2013</p>
	</c:if>
	<c:if test="${invalidBrand}">
		<p class="warning">Missing brand</p>
	</c:if>
	<c:if test="${invalidFuel}">
		<p class="warning">Invalid fuel consumption, must be between 0.1
			and 3.0</p>
	</c:if>
	<c:if test="${invalidOwner}">
		<p class="warning">Missing owner</p>
	</c:if>


	<div class="table">
		<form
			action='<c:url value="/plusverkstaden/editCar.servlet"></c:url>'
			method="POST">

			<table class="info">
				<tr>
					<th>Reg no</th>
					<td><c:if test="${newCar}">
							<input type="text" name="reg" value="${car.regNo}">
						</c:if> <c:if test="${not newCar}">
				${car.regNo}<input type="hidden" name="reg" value="${car.regNo}">
						</c:if></td>
				</tr>
				<tr>
					<th>Year</th>
					<td><input type="text" name="year" value="${car.yearModel}"></td>
				</tr>
				<tr>
					<th>Brand</th>
					<td><select name="brand">

							<c:if test="${newCar}">
								<option value="empty"></option>
							</c:if>

							<c:forEach var="brand" items="${brands}">
								<c:set var="selected" value=""></c:set>
								<c:if test="${car.brand eq brand}">
									<c:set var="selected" value="selected"></c:set>
								</c:if>

								<option value='<c:out value="${brand}" />' ${selected}><c:out
										value="${brand.niceName}" />
								</option>
							</c:forEach>
					</select></td>
				</tr>
				<tr>
					<th>Fuel consumption</th>
					<td><input type="text" name="fuel"
						value="${car.fuelConsumption}"></td>
				</tr>
				<tr>
					<th>Owner</th>
					<td><select name="owner">

							<c:if test="${newCar}">
								<option value="empty"></option>
							</c:if>

							<c:forEach var="owner" items="${owners}">
								<c:set var="selected" value=""></c:set>
								<c:if test="${car.owner eq owner}">
									<c:set var="selected" value="selected"></c:set>
								</c:if>

								<option value='<c:out value="${owner.socialSecurityNo}" />'
									${selected}><c:out value="${owner.fullName}" />
								</option>
							</c:forEach>
					</select></td>
				</tr>

			</table>


			<input id="submit" type="submit" value="${submit}"> <a
				href='<c:url value="/plusverkstaden/listCars.servlet" />' class="button">Cancel</a>

		</form>
	</div>
	<jsp:include page="footer.jsp"></jsp:include>

</body>
</html>

WebContent/WEB-INF/jsp/plusverkstaden/ListCars.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
    
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="myDate" uri="myFunctions" %>
<%@ taglib prefix="myTags" tagdir="/WEB-INF/tags/plusverkstaden"%>
<%@ page import="java.util.*"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>List Cars</title>
<link rel="stylesheet"
	href="<%=request.getContextPath()%>/styles/Cars.css">
</head>
<body>
	<jsp:include page="header.jsp">
		<jsp:param value="List cars" name="title"/>
		<jsp:param value="${myDate:today()}" name="date"/>
	</jsp:include>
	
	<nav>
		<a href='<c:url value="/plusverkstaden/editCar.servlet" />' class="button">Add new car</a>
	</nav>
	
	<myTags:carList cars="${cars}"/>
	
	<jsp:include page="footer.jsp"></jsp:include>	
</body>
</html>

WebContent/WEB-INF/jsp/plusverkstaden/ShowCar.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
    
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="myDate" uri="myFunctions" %>
<%@ page import="java.util.*"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Show Cars</title>
<link rel="stylesheet"
	href="<%=request.getContextPath()%>/styles/Cars.css">
</head>
<body>
	<jsp:include page="header.jsp">
		<jsp:param value="Show car: ${car.regNo }" name="title"/>
		<jsp:param value="${myDate:today()}" name="date"/>
	</jsp:include>

	

	<div class=table id=car>
		<h2>Car</h2>
		<table class=info>
			<tr>
				<th>Reg number</th>
				<td>${car.regNo }</td>
			</tr>
			<tr>
				<th>Year model</th>
				<td>${car.yearModel }</td>
			</tr>
			<tr>
				<th>Brand</th>
				<td>${car.brand.niceName }</td>
			</tr>
			<tr>
				<th>Fuel consumption</th>
				<td>${car.fuelConsumption }</td>
			</tr>
	
		</table>
	</div>
	
	<div class=table id=owner>
		<h2>Owner</h2>
		<table class=info>
			<tr>
				<th>First name</th>
				<td>${car.owner.firstName }</td>
			</tr>
			<tr>
				<th>Last name</th>
				<td>${car.owner.lastName }</td>
			</tr>
			<tr>
				<th>Address</th>
				<td>${car.owner.address }</td>
			</tr>
			<tr>
				<th>Zip code</th>
				<td>${car.owner.zipCode}</td>
			</tr>
			<tr>
				<th>City</th>
				<td>${car.owner.city}</td>
			</tr>
			
		
		</table>
	
	</div>

	<nav>
		
		<a href='<c:url value="/plusverkstaden/editCar.servlet?regNo=${car.regNo }" />' class="button">Edit Car</a>
		<a href='<c:url value="/plusverkstaden/listCars.servlet" />' class="button">Cancel</a>
	</nav>
		
	<jsp:include page="footer.jsp"></jsp:include>

</body>
</html>

WebContent/WEB-INF/jsp/plusverkstaden/footer.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

<footer>
	<h4>Recently edited cars</h4>
	<ul>
		<c:forEach var="carWithName" items="${carsWithNames}">
		<li>
			<c:out value="${carWithName}"></c:out>
		</li>
		</c:forEach>	
	</ul>
</footer>

WebContent/WEB-INF/jsp/plusverkstaden/header.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

<header>
		<h1><a href='<c:url value="non/exsisting/page"/>' >PlusVerkstaden</a></h1>
		<p id="title">${param.title}</p>
		<p id="date">Todays date is: ${param.date}</p>
		<a href='<c:url value="/plusverkstaden/listCars.servlet"/>' class="button">Home</a>
</header>